---
title: "US Crime Data"
output: 
  flexdashboard::flex_dashboard:
    css: styles_Shiny.css
runtime: shiny
---


```{r Setup, include=FALSE}
# Loading necessary libraries
library(tidyverse)
library(RColorBrewer)
library(plotly)
library(maps)
library(httr)
library(shiny)
library(flexdashboard)
library(rgdal)
library(maptools)
library(sp)


knitr::opts_chunk$set(message = FALSE, warning = FALSE)


# Loading Data
load(file = "./data/Crime_In_US_By_State//data_state_time.RData")
```



Crime Rates By State
===================================== 

Column {.sidebar data-width=310}
-----------------------------------------------------------------------

```{r Sidebar_Crime_Data_State}
crime_forms_state = c(
  "aggravated assault",
  "burglary",
  "larceny-theft",
  "motor vehicle theft",
  "murder and nonnegligent manslaughter",
  "rape",
  "robbery")
  
selectInput(
  "crime_form_state", 
  label = h3("Choose Type of Crime"),
  choices = as.list(crime_forms_state))
```

 

Column {.tabset}
-------------------------------------

### Map

```{r Map_State}
renderPlotly({

  col = colorRampPalette(brewer.pal(9, "BuPu"))(200)
  
  geo = list(
      scope = "usa",
      projection = list(type = "state"),
      showlakes = FALSE,
      lakecolor = toRGB("white"))
  
  altered_input_crime_form_state = str_replace_all(input$crime_form_state, " ", "_")
  altered_input_crime_form_state = str_replace_all(altered_input_crime_form_state, "-", "_")
  
  min_z = data_state %>% 
    filter(variable_name == paste(altered_input_crime_form_state, "_rate_per_100_000", sep = "")) %>%
    pull(statistic) %>% 
    min() %>% 
    floor()
  
  max_z = data_state %>% 
    filter(variable_name == paste(altered_input_crime_form_state, "_rate_per_100_000", sep = "")) %>%
    pull(statistic) %>% 
    max() %>% 
    ceiling()
  
  
  data_state %>%
    filter(variable_name == paste(altered_input_crime_form_state, "_rate_per_100_000", sep = "")) %>%
    plot_geo(locationmode = "USA-states") %>%
    add_trace(
      z = ~statistic,
      zmin = min_z,
      zmax = max_z,
      locations = ~state_code,
      color = ~statistic,
      colors = col,
      frame = ~year,
      text =  ~paste(
        paste("State: ", state, sep = ""),
        "\n" ,
        paste("Year: ", year, sep = ""), 
        sep = ""),
        hovertemplate = "%{text}\nStatistic: %{z}<extra></extra>") %>%
    layout(
      geo = geo,
      title = paste(
        "<b>\n", 
        input$crime_form_state, 
        " - rate per 100,000 people </b>", 
        sep = ""), 
      titlefont = list(size = 16)) %>%
    animation_opts(
      frame = 1200, 
      transition = 10,
      easing = "elastic", 
      redraw = TRUE)
})
```


### Time Plot

```{r Time_Plot_State}
states_available = data_state %>% 
  arrange(state) %>% 
  pull(state) %>% 
  unique()
states_available = c("All States", states_available)

selectInput(
  "state_chosen", 
  label = h3("Choose State"),
  choices = as.list(states_available))

renderPlotly({
  
  altered_input_crime_form_state = str_replace_all(input$crime_form_state, " ", "_")
  altered_input_crime_form_state = str_replace_all(altered_input_crime_form_state, "-", "_")

  if (input$state_chosen != "All States") {
  
    data_state %>%
      filter(state == input$state_chosen) %>%
      filter(variable_name == paste(altered_input_crime_form_state, "_rate_per_100_000", sep = "")) %>% 
      plot_ly(
        x = ~year, 
        y = ~statistic, 
        type = "scatter", 
        mode = 'lines+markers',
        alpha = 0.9,
        text =  ~paste("State: ", state, sep = ""),
        hovertemplate = "%{text}\nYear: %{x}\nStatistic: %{y}<extra></extra>") %>%
      layout(
        height = 450,
        xaxis = list(
          title = "Year",
          dtick = 2,
          tick0 = 1999,
          range = c(1998, 2019),
          tickmode = "linear",
          titlefont = list(size = 13),
          tickfont = list(size = 11)),
        yaxis = list(
          title = ~paste(input$crime_form_state, "\nrate per 100,000 people\n" ,sep = " "),
          titlefont = list(size = 13),
          tickfont = list(size = 11)),
        title =  ~paste("\n",input$state_chosen, "\n", sep = ""),
        titlefont = list(size = 17))
  }
  
  else {
    
    data_state %>%
      filter(variable_name == paste(altered_input_crime_form_state, "_rate_per_100_000", sep = "")) %>% 
      plot_ly(
        x = ~year, 
        y = ~statistic, 
        type = "scatter", 
        mode = 'lines+markers',
        alpha = 0.75,
        color = ~as.factor(state),
        text =  ~paste("State: ", state, sep = ""),
        hovertemplate = "%{text}\nYear: %{x}\nStatistic: %{y}<extra></extra>") %>%
      layout(
        height = 450,
        xaxis = list(
          title = "Year",
          dtick = 2,
          tick0 = 1999,
          range = c(1998, 2019),
          tickmode = "linear",
          titlefont = list(size = 13),
          tickfont = list(size = 11)),
        yaxis = list(
          title = ~paste(input$crime_form_state, "\nrate per 100,000 people\n" ,sep = " "),
          titlefont = list(size = 13),
          tickfont = list(size = 11)))
  }
})
```

 
 
 
Crime Rates By Regions / Divisions
===================================== 



Column {.sidebar data-width=310}
-----------------------------------------------------------------------

```{r Sidebar_Crime_Data_Region}

```
 

Column {.tabset}
-------------------------------------

### Map

```{r Map_Region}

```


### Time Plot

```{r Time_Plot_Region}

```

 

 
 
 
 
Clearance Rates By Regions / Divisions
===================================== 


Column {.sidebar data-width=310}
-----------------------------------------------------------------------

```{r Sidebar_Clearance_Region}

```



Column {.tabset}
-------------------------------------

### Map

```{r Map_Region_Clearance}


```


 
### Time Plot

```{r Time_plot_Region_Clearance}
 
 
```



Murder Weapons By State
===================================== 


Column {.sidebar data-width=310}
-----------------------------------------------------------------------

```{r Sidebar_Murder_Weapon}


```




Column {data-width=800}
-------------------------------------
    
### 
    
```{r Murder_Weapon_Plot}


```
 
 
 
 
NYC Crime Rates 
===================================== 


Column {.sidebar data-width=310}
-----------------------------------------------------------------------

```{r Sidebar_Crime_Data_NYC}


```



Column {.tabset}
-------------------------------------

### Map

```{r Map_NYC}


```

### Time Plot
 
```{r Time_Plot_NYC}


```


About 
=====================================
